### ISSUE TITLE
Suggestion for modules 

### ISSUE THREAD

**Issue by Ghost861** [SaberAspect/SpectClient#2]
Add crystal aura 
And elytra fly with some bypasses for popular servers such as 8b8t and a targethud
Add phase 
And baritone support

**Comment by SaberAspect** [comment]
isnt 8b8t on 1.15.2?

**Comment by SaberAspect** [comment]
phase, and elytra fly may come in 0.5.2-0.5.3 but CA and baritone support will definitely be down the road.
I would like to get CA in as soon as possible definitely.

**Comment by Ghost861** [comment]
> isnt 8b8t on 1.15.2?
> or am I thinking of 8b8t.net?

Nah its 1.12 I'm talking about 8b8t.xyz

**Comment by Ghost861** [comment]
> phase, and elytra fly may come in 0.5.2-0.5.3 but CA and baritone support will definitely be down the road.
> I would like to get CA in as soon as possible definitely.

Yeah baritone isnt a must but efly and ca is especially for a 1.12 client
